# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matmul_dense_csc_numeric <- function(X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads) {
    .Call(`_MatrixExtra_matmul_dense_csc_numeric`, X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads)
}

matmul_dense_csc_float32 <- function(X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads) {
    .Call(`_MatrixExtra_matmul_dense_csc_float32`, X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads)
}

tcrossprod_dense_csr_numeric <- function(X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y) {
    .Call(`_MatrixExtra_tcrossprod_dense_csr_numeric`, X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y)
}

tcrossprod_dense_csr_float32 <- function(X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y) {
    .Call(`_MatrixExtra_tcrossprod_dense_csr_float32`, X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y)
}

tcrossprod_csr_dense_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads) {
    .Call(`_MatrixExtra_tcrossprod_csr_dense_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads)
}

tcrossprod_csr_dense_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads) {
    .Call(`_MatrixExtra_tcrossprod_csr_dense_float32`, X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads)
}

matmul_csr_dvec_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_float32`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_svec_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_binary <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_binary`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, nthreads)
}

matmul_csr_svec_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_float32`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_colvec_by_srowvecascsc <- function(colvec_, indptr, indices, values) {
    .Call(`_MatrixExtra_matmul_colvec_by_srowvecascsc`, colvec_, indptr, indices, values)
}

matmul_colvec_by_srowvecascsc_binary <- function(colvec_, indptr, indices) {
    .Call(`_MatrixExtra_matmul_colvec_by_srowvecascsc_binary`, colvec_, indptr, indices)
}

matmul_rowvec_by_csc <- function(rowvec_, indptr, indices, values) {
    .Call(`_MatrixExtra_matmul_rowvec_by_csc`, rowvec_, indptr, indices, values)
}

matmul_rowvec_by_cscbin <- function(rowvec_, indptr, indices) {
    .Call(`_MatrixExtra_matmul_rowvec_by_cscbin`, rowvec_, indptr, indices)
}

matmul_colvec_by_drowvecascsc <- function(colvec_, indptr, indices, values_) {
    .Call(`_MatrixExtra_matmul_colvec_by_drowvecascsc`, colvec_, indptr, indices, values_)
}

matmul_colvec_by_scolvecascsr_f32 <- function(colvec_, indptr, indices, values) {
    .Call(`_MatrixExtra_matmul_colvec_by_scolvecascsr_f32`, colvec_, indptr, indices, values)
}

matmul_colvec_by_scolvecascsr <- function(colvec_, indptr, indices, values_) {
    .Call(`_MatrixExtra_matmul_colvec_by_scolvecascsr`, colvec_, indptr, indices, values_)
}

matmul_spcolvec_by_scolvecascsr_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_binary <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_binary`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_length)
}

is_same_ngRMatrix <- function(indptr1, indptr2, indices1, indices2) {
    .Call(`_MatrixExtra_is_same_ngRMatrix`, indptr1, indptr2, indices1, indices2)
}

sort_sparse_indices_numeric <- function(indptr, indices, values) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_numeric`, indptr, indices, values))
}

sort_sparse_indices_logical <- function(indptr, indices, values) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_logical`, indptr, indices, values))
}

sort_sparse_indices_binary <- function(indptr, indices) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_binary`, indptr, indices))
}

sort_coo_indices_numeric <- function(indices1, indices2, values) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_numeric`, indices1, indices2, values))
}

sort_coo_indices_logical <- function(indices1, indices2, values) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_logical`, indices1, indices2, values))
}

sort_coo_indices_binary <- function(indices1, indices2) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_binary`, indices1, indices2))
}

sort_vector_indices_numeric <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_numeric`, indices_base1, values))
}

sort_vector_indices_integer <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_integer`, indices_base1, values))
}

sort_vector_indices_logical <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_logical`, indices_base1, values))
}

sort_vector_indices_binary <- function(indices_base1) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_binary`, indices_base1))
}

multiply_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2) {
    .Call(`_MatrixExtra_multiply_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2)
}

multiply_csr_by_dense_elemwise_double <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_double`, indptr, indices, values, dense_mat)
}

multiply_csr_by_dense_elemwise_int <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_int`, indptr, indices, values, dense_mat)
}

multiply_csr_by_dense_elemwise_bool <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_bool`, indptr, indices, values, dense_mat)
}

add_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2, substract) {
    .Call(`_MatrixExtra_add_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2, substract)
}

concat_indptr2 <- function(ptr1, ptr2) {
    .Call(`_MatrixExtra_concat_indptr2`, ptr1, ptr2)
}

concat_csr_batch <- function(objects, out) {
    .Call(`_MatrixExtra_concat_csr_batch`, objects, out)
}

check_is_seq <- function(indices) {
    .Call(`_MatrixExtra_check_is_seq`, indices)
}

copy_csr_rows <- function(indptr, indices, values, rows_take) {
    .Call(`_MatrixExtra_copy_csr_rows`, indptr, indices, values, rows_take)
}

copy_csr_rows_col_seq <- function(indptr, indices, values, rows_take, cols_take) {
    .Call(`_MatrixExtra_copy_csr_rows_col_seq`, indptr, indices, values, rows_take, cols_take)
}

copy_csr_arbitrary <- function(indptr, indices, values, rows_take, cols_take) {
    .Call(`_MatrixExtra_copy_csr_arbitrary`, indptr, indices, values, rows_take, cols_take)
}

repeat_indices_n_times <- function(indices, remainder, ix_length, desired_length) {
    .Call(`_MatrixExtra_repeat_indices_n_times`, indices, remainder, ix_length, desired_length)
}

