# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_single_row_to_zero <- function(indptr, indices, values, row_set) {
    .Call(`_MatrixExtra_set_single_row_to_zero`, indptr, indices, values, row_set)
}

set_single_col_to_zero <- function(indptr, indices, values, col_set) {
    .Call(`_MatrixExtra_set_single_col_to_zero`, indptr, indices, values, col_set)
}

set_single_row_to_const <- function(indptr, indices, values, ncols, row_set, val_set) {
    .Call(`_MatrixExtra_set_single_row_to_const`, indptr, indices, values, ncols, row_set, val_set)
}

set_single_col_to_const <- function(indptr, indices, values, ncols, col_set, val_set) {
    .Call(`_MatrixExtra_set_single_col_to_const`, indptr, indices, values, ncols, col_set, val_set)
}

set_single_val_to_zero <- function(indptr, indices, values, row_set, col_set) {
    .Call(`_MatrixExtra_set_single_val_to_zero`, indptr, indices, values, row_set, col_set)
}

set_single_val_to_const <- function(indptr, indices, values, ncols, row_set, col_set, val_set) {
    .Call(`_MatrixExtra_set_single_val_to_const`, indptr, indices, values, ncols, row_set, col_set, val_set)
}

set_single_row_to_rowvec <- function(indptr, indices, values, ncols, row_set, vec_set) {
    .Call(`_MatrixExtra_set_single_row_to_rowvec`, indptr, indices, values, ncols, row_set, vec_set)
}

set_single_col_to_colvec <- function(indptr, indices, values, ncols, col_set, vec_set) {
    .Call(`_MatrixExtra_set_single_col_to_colvec`, indptr, indices, values, ncols, col_set, vec_set)
}

set_single_row_to_svec <- function(indptr, indices, values, ncols, row_set, ii, xx, length) {
    .Call(`_MatrixExtra_set_single_row_to_svec`, indptr, indices, values, ncols, row_set, ii, xx, length)
}

set_single_col_to_svec <- function(indptr, indices, values, ncols, col_set, ii, xx, length) {
    .Call(`_MatrixExtra_set_single_col_to_svec`, indptr, indices, values, ncols, col_set, ii, xx, length)
}

set_rowseq_to_zero <- function(indptr, indices, values, row_set_st, row_set_end) {
    .Call(`_MatrixExtra_set_rowseq_to_zero`, indptr, indices, values, row_set_st, row_set_end)
}

set_rowseq_to_const <- function(indptr, indices, values, row_set_st, row_set_end, ncols, val_set) {
    .Call(`_MatrixExtra_set_rowseq_to_const`, indptr, indices, values, row_set_st, row_set_end, ncols, val_set)
}

set_colseq_to_zero <- function(indptr, indices, values, col_set_st, col_set_end, ncols) {
    .Call(`_MatrixExtra_set_colseq_to_zero`, indptr, indices, values, col_set_st, col_set_end, ncols)
}

set_colseq_to_const <- function(indptr, indices, values, col_set_st, col_set_end, ncols, val_set) {
    .Call(`_MatrixExtra_set_colseq_to_const`, indptr, indices, values, col_set_st, col_set_end, ncols, val_set)
}

set_arbitrary_rows_to_zero <- function(indptr, indices, values, rows_set) {
    .Call(`_MatrixExtra_set_arbitrary_rows_to_zero`, indptr, indices, values, rows_set)
}

set_arbitrary_rows_to_const <- function(indptr, indices, values, rows_set, ncols, val_set) {
    .Call(`_MatrixExtra_set_arbitrary_rows_to_const`, indptr, indices, values, rows_set, ncols, val_set)
}

set_arbitrary_cols_to_zero <- function(indptr, indices, values, cols_set, ncols) {
    .Call(`_MatrixExtra_set_arbitrary_cols_to_zero`, indptr, indices, values, cols_set, ncols)
}

set_arbitrary_cols_to_const <- function(indptr, indices, values, cols_set, ncols, val_set) {
    .Call(`_MatrixExtra_set_arbitrary_cols_to_const`, indptr, indices, values, cols_set, ncols, val_set)
}

set_arbitrary_rows_single_col_to_zero <- function(indptr, indices, values, rows_set, col_set, ncols) {
    .Call(`_MatrixExtra_set_arbitrary_rows_single_col_to_zero`, indptr, indices, values, rows_set, col_set, ncols)
}

set_arbitrary_rows_single_col_to_const <- function(indptr, indices, values, rows_set, col_set, val_set, ncols) {
    .Call(`_MatrixExtra_set_arbitrary_rows_single_col_to_const`, indptr, indices, values, rows_set, col_set, val_set, ncols)
}

set_single_row_arbitrary_cols_to_zero <- function(indptr, indices, values, row_set, cols_set, ncols) {
    .Call(`_MatrixExtra_set_single_row_arbitrary_cols_to_zero`, indptr, indices, values, row_set, cols_set, ncols)
}

set_single_row_arbitrary_cols_to_const <- function(indptr, indices, values, row_set, cols_set, ncols, val_set) {
    .Call(`_MatrixExtra_set_single_row_arbitrary_cols_to_const`, indptr, indices, values, row_set, cols_set, ncols, val_set)
}

set_arbitrary_rows_arbitrary_cols_to_zero <- function(indptr, indices, values, rows_set, cols_set, ncols) {
    .Call(`_MatrixExtra_set_arbitrary_rows_arbitrary_cols_to_zero`, indptr, indices, values, rows_set, cols_set, ncols)
}

set_arbitrary_rows_arbitrary_cols_to_const <- function(indptr, indices, values, rows_set, cols_set, ncols, val_set) {
    .Call(`_MatrixExtra_set_arbitrary_rows_arbitrary_cols_to_const`, indptr, indices, values, rows_set, cols_set, ncols, val_set)
}

set_rowseq_to_smat <- function(indptr, indices, values, row_set_st, row_set_end, indptr_other, indices_other, values_other) {
    .Call(`_MatrixExtra_set_rowseq_to_smat`, indptr, indices, values, row_set_st, row_set_end, indptr_other, indices_other, values_other)
}

set_arbitrary_rows_to_smat <- function(indptr, indices, values, rows_set, indptr_other, indices_other, values_other) {
    .Call(`_MatrixExtra_set_arbitrary_rows_to_smat`, indptr, indices, values, rows_set, indptr_other, indices_other, values_other)
}

cbind_csr_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_csr_indptr, Y_csr_indices_plus_ncol, Y_csr_values) {
    .Call(`_MatrixExtra_cbind_csr_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, Y_csr_indptr, Y_csr_indices_plus_ncol, Y_csr_values)
}

cbind_csr_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_csr_indptr, Y_csr_indices_plus_ncol, Y_csr_values) {
    .Call(`_MatrixExtra_cbind_csr_logical`, X_csr_indptr, X_csr_indices, X_csr_values, Y_csr_indptr, Y_csr_indices_plus_ncol, Y_csr_values)
}

cbind_csr_binary <- function(X_csr_indptr, X_csr_indices, Y_csr_indptr, Y_csr_indices_plus_ncol) {
    .Call(`_MatrixExtra_cbind_csr_binary`, X_csr_indptr, X_csr_indices, Y_csr_indptr, Y_csr_indices_plus_ncol)
}

matmul_dense_csc_numeric <- function(X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads) {
    .Call(`_MatrixExtra_matmul_dense_csc_numeric`, X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads)
}

matmul_dense_csc_float32 <- function(X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads) {
    .Call(`_MatrixExtra_matmul_dense_csc_float32`, X_colmajor, Y_csc_indptr, Y_csc_indices, Y_csc_values, nthreads)
}

tcrossprod_dense_csr_numeric <- function(X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y) {
    .Call(`_MatrixExtra_tcrossprod_dense_csr_numeric`, X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y)
}

tcrossprod_dense_csr_float32 <- function(X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y) {
    .Call(`_MatrixExtra_tcrossprod_dense_csr_float32`, X_colmajor, Y_csr_indptr, Y_csr_indices, Y_csr_values, nthreads, ncols_Y)
}

tcrossprod_csr_dense_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads) {
    .Call(`_MatrixExtra_tcrossprod_csr_dense_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads)
}

tcrossprod_csr_dense_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads) {
    .Call(`_MatrixExtra_tcrossprod_csr_dense_float32`, X_csr_indptr, X_csr_indices, X_csr_values, Y_colmajor, nthreads)
}

matmul_csr_dvec_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_dvec_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_dvec_float32`, X_csr_indptr, X_csr_indices, X_csr_values, y_dense, nthreads)
}

matmul_csr_svec_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_csr_svec_binary <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_binary`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, nthreads)
}

matmul_csr_svec_float32 <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads) {
    .Call(`_MatrixExtra_matmul_csr_svec_float32`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, nthreads)
}

matmul_rowvec_by_csc <- function(rowvec_, indptr, indices, values) {
    .Call(`_MatrixExtra_matmul_rowvec_by_csc`, rowvec_, indptr, indices, values)
}

matmul_rowvec_by_cscbin <- function(rowvec_, indptr, indices) {
    .Call(`_MatrixExtra_matmul_rowvec_by_cscbin`, rowvec_, indptr, indices)
}

matmul_colvec_by_scolvecascsr_f32 <- function(colvec_, indptr, indices, values_) {
    .Call(`_MatrixExtra_matmul_colvec_by_scolvecascsr_f32`, colvec_, indptr, indices, values_)
}

matmul_colvec_by_scolvecascsr <- function(colvec_, indptr, indices, values_) {
    .Call(`_MatrixExtra_matmul_colvec_by_scolvecascsr`, colvec_, indptr, indices, values_)
}

matmul_spcolvec_by_scolvecascsr_numeric <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_numeric`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_integer <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_integer`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_logical <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_logical`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_values, y_length)
}

matmul_spcolvec_by_scolvecascsr_binary <- function(X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_length) {
    .Call(`_MatrixExtra_matmul_spcolvec_by_scolvecascsr_binary`, X_csr_indptr, X_csr_indices, X_csr_values, y_indices_base1, y_length)
}

contains_any_zero <- function(x) {
    .Call(`_MatrixExtra_contains_any_zero`, x)
}

contains_any_inf <- function(x) {
    .Call(`_MatrixExtra_contains_any_inf`, x)
}

contains_any_neg <- function(x) {
    .Call(`_MatrixExtra_contains_any_neg`, x)
}

is_same_ngRMatrix <- function(indptr1, indptr2, indices1, indices2) {
    .Call(`_MatrixExtra_is_same_ngRMatrix`, indptr1, indptr2, indices1, indices2)
}

check_is_sorted <- function(x) {
    .Call(`_MatrixExtra_check_is_sorted`, x)
}

check_indices_are_unsorted <- function(indptr, indices) {
    .Call(`_MatrixExtra_check_indices_are_unsorted`, indptr, indices)
}

sort_sparse_indices_numeric <- function(indptr, indices, values) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_numeric`, indptr, indices, values))
}

sort_sparse_indices_logical <- function(indptr, indices, values) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_logical`, indptr, indices, values))
}

sort_sparse_indices_numeric_known_ncol <- function(indptr, indices, values, ncol) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_numeric_known_ncol`, indptr, indices, values, ncol))
}

sort_sparse_indices_logical_known_ncol <- function(indptr, indices, values, ncol) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_logical_known_ncol`, indptr, indices, values, ncol))
}

sort_sparse_indices_binary <- function(indptr, indices) {
    invisible(.Call(`_MatrixExtra_sort_sparse_indices_binary`, indptr, indices))
}

sort_coo_indices_numeric <- function(indices1, indices2, values) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_numeric`, indices1, indices2, values))
}

sort_coo_indices_logical <- function(indices1, indices2, values) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_logical`, indices1, indices2, values))
}

sort_coo_indices_binary <- function(indices1, indices2) {
    invisible(.Call(`_MatrixExtra_sort_coo_indices_binary`, indices1, indices2))
}

sort_vector_indices_numeric <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_numeric`, indices_base1, values))
}

sort_vector_indices_integer <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_integer`, indices_base1, values))
}

sort_vector_indices_logical <- function(indices_base1, values) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_logical`, indices_base1, values))
}

sort_vector_indices_binary <- function(indices_base1) {
    invisible(.Call(`_MatrixExtra_sort_vector_indices_binary`, indices_base1))
}

deepcopy_num <- function(x) {
    .Call(`_MatrixExtra_deepcopy_num`, x)
}

deepcopy_int <- function(x) {
    .Call(`_MatrixExtra_deepcopy_int`, x)
}

deepcopy_log <- function(x) {
    .Call(`_MatrixExtra_deepcopy_log`, x)
}

deepcopy_str <- function(x) {
    .Call(`_MatrixExtra_deepcopy_str`, x)
}

remove_zero_valued_csr_numeric <- function(indptr, indices, values, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_csr_numeric`, indptr, indices, values, remove_NAs)
}

remove_zero_valued_csr_logical <- function(indptr, indices, values, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_csr_logical`, indptr, indices, values, remove_NAs)
}

remove_zero_valued_coo_numeric <- function(ii, jj, xx, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_coo_numeric`, ii, jj, xx, remove_NAs)
}

remove_zero_valued_coo_logical <- function(ii, jj, xx, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_coo_logical`, ii, jj, xx, remove_NAs)
}

remove_zero_valued_svec_numeric <- function(ii, xx, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_svec_numeric`, ii, xx, remove_NAs)
}

remove_zero_valued_svec_integer <- function(ii, xx, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_svec_integer`, ii, xx, remove_NAs)
}

remove_zero_valued_svec_logical <- function(ii, xx, remove_NAs) {
    .Call(`_MatrixExtra_remove_zero_valued_svec_logical`, ii, xx, remove_NAs)
}

check_valid_csr_matrix <- function(indptr, indices, nrows, ncols) {
    .Call(`_MatrixExtra_check_valid_csr_matrix`, indptr, indices, nrows, ncols)
}

check_valid_coo_matrix <- function(ii, jj, nrows, ncols) {
    .Call(`_MatrixExtra_check_valid_coo_matrix`, ii, jj, nrows, ncols)
}

check_valid_svec <- function(ii, nrows) {
    .Call(`_MatrixExtra_check_valid_svec`, ii, nrows)
}

multiply_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2) {
    .Call(`_MatrixExtra_multiply_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2)
}

logicaland_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2) {
    .Call(`_MatrixExtra_logicaland_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2)
}

multiply_csr_by_dense_elemwise_double <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_double`, indptr, indices, values, dense_mat)
}

multiply_csr_by_dense_elemwise_float32 <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_float32`, indptr, indices, values, dense_mat)
}

multiply_csr_by_dense_elemwise_int <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_int`, indptr, indices, values, dense_mat)
}

multiply_csr_by_dense_elemwise_bool <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_multiply_csr_by_dense_elemwise_bool`, indptr, indices, values, dense_mat)
}

logicaland_csr_by_dense_cpp <- function(indptr, indices, values, dense_mat) {
    .Call(`_MatrixExtra_logicaland_csr_by_dense_cpp`, indptr, indices, values, dense_mat)
}

add_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2, substract) {
    .Call(`_MatrixExtra_add_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2, substract)
}

logicalor_csr_elemwise <- function(indptr1, indptr2, indices1, indices2, values1, values2, xor_op) {
    .Call(`_MatrixExtra_logicalor_csr_elemwise`, indptr1, indptr2, indices1, indices2, values1, values2, xor_op)
}

multiply_csr_by_coo_elemwise <- function(X_csr_indptr_, X_csr_indices_, X_csr_values_, Y_coo_row, Y_coo_col, Y_coo_val, max_row_X, max_col_X) {
    .Call(`_MatrixExtra_multiply_csr_by_coo_elemwise`, X_csr_indptr_, X_csr_indices_, X_csr_values_, Y_coo_row, Y_coo_col, Y_coo_val, max_row_X, max_col_X)
}

logicaland_csr_by_coo_elemwise <- function(X_csr_indptr_, X_csr_indices_, X_csr_values_, Y_coo_row, Y_coo_col, Y_coo_val, max_row_X, max_col_X) {
    .Call(`_MatrixExtra_logicaland_csr_by_coo_elemwise`, X_csr_indptr_, X_csr_indices_, X_csr_values_, Y_coo_row, Y_coo_col, Y_coo_val, max_row_X, max_col_X)
}

multiply_coo_by_dense_numeric <- function(X_, Y_coo_row, Y_coo_col, Y_coo_val) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_numeric`, X_, Y_coo_row, Y_coo_col, Y_coo_val)
}

multiply_coo_by_dense_integer <- function(X_, Y_coo_row, Y_coo_col, Y_coo_val) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_integer`, X_, Y_coo_row, Y_coo_col, Y_coo_val)
}

multiply_coo_by_dense_logical <- function(X_, Y_coo_row, Y_coo_col, Y_coo_val) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_logical`, X_, Y_coo_row, Y_coo_col, Y_coo_val)
}

multiply_coo_by_dense_float32 <- function(X_, Y_coo_row, Y_coo_col, Y_coo_val) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_float32`, X_, Y_coo_row, Y_coo_col, Y_coo_val)
}

logicaland_coo_by_dense_logical <- function(X_, Y_coo_row, Y_coo_col, Y_coo_val) {
    .Call(`_MatrixExtra_logicaland_coo_by_dense_logical`, X_, Y_coo_row, Y_coo_col, Y_coo_val)
}

add_NAs_from_dense_after_elemenwise_mult_numeric <- function(indptr, indices, dense_) {
    .Call(`_MatrixExtra_add_NAs_from_dense_after_elemenwise_mult_numeric`, indptr, indices, dense_)
}

add_NAs_from_dense_after_elemenwise_mult_integer <- function(indptr, indices, dense_) {
    .Call(`_MatrixExtra_add_NAs_from_dense_after_elemenwise_mult_integer`, indptr, indices, dense_)
}

add_NAs_from_dense_after_elemenwise_mult_float32 <- function(indptr, indices, dense_) {
    .Call(`_MatrixExtra_add_NAs_from_dense_after_elemenwise_mult_float32`, indptr, indices, dense_)
}

add_NAs_from_dense_after_elemenwise_mult_logical <- function(indptr, indices, dense_) {
    .Call(`_MatrixExtra_add_NAs_from_dense_after_elemenwise_mult_logical`, indptr, indices, dense_)
}

multiply_csc_by_dense_ignore_NAs_numeric <- function(indptr, indices, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_ignore_NAs_numeric`, indptr, indices, values, dense_)
}

multiply_csc_by_dense_ignore_NAs_float32 <- function(indptr, indices, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_ignore_NAs_float32`, indptr, indices, values, dense_)
}

multiply_csc_by_dense_ignore_NAs_integer <- function(indptr, indices, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_ignore_NAs_integer`, indptr, indices, values, dense_)
}

multiply_csc_by_dense_ignore_NAs_logical <- function(indptr, indices, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_ignore_NAs_logical`, indptr, indices, values, dense_)
}

logicaland_csc_by_dense_ignore_NAs <- function(indptr, indices, values, dense_) {
    .Call(`_MatrixExtra_logicaland_csc_by_dense_ignore_NAs`, indptr, indices, values, dense_)
}

multiply_csc_by_dense_keep_NAs_numeric <- function(indptr, indices_, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_keep_NAs_numeric`, indptr, indices_, values, dense_)
}

multiply_csc_by_dense_keep_NAs_integer <- function(indptr, indices_, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_keep_NAs_integer`, indptr, indices_, values, dense_)
}

multiply_csc_by_dense_keep_NAs_logical <- function(indptr, indices_, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_keep_NAs_logical`, indptr, indices_, values, dense_)
}

multiply_csc_by_dense_keep_NAs_float32 <- function(indptr, indices_, values, dense_) {
    .Call(`_MatrixExtra_multiply_csc_by_dense_keep_NAs_float32`, indptr, indices_, values, dense_)
}

logicaland_csc_by_dense_keep_NAs <- function(indptr, indices_, values, dense_) {
    .Call(`_MatrixExtra_logicaland_csc_by_dense_keep_NAs`, indptr, indices_, values, dense_)
}

multiply_csr_by_dvec_no_NAs_numeric <- function(indptr, indices, values, dvec, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS) {
    .Call(`_MatrixExtra_multiply_csr_by_dvec_no_NAs_numeric`, indptr, indices, values, dvec, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS)
}

logicaland_csr_by_dvec_internal <- function(indptr, indices, values, dvec, ncols) {
    .Call(`_MatrixExtra_logicaland_csr_by_dvec_internal`, indptr, indices, values, dvec, ncols)
}

multiply_csr_by_dvec_with_NAs <- function(indptr, indices, values, dvec, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS) {
    .Call(`_MatrixExtra_multiply_csr_by_dvec_with_NAs`, indptr, indices, values, dvec, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS)
}

multiply_coo_by_dense_ignore_NAs_numeric <- function(ii, jj, xx, dvec, nrows, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_ignore_NAs_numeric`, ii, jj, xx, dvec, nrows, ncols, multiply, powerto, divide, divrest, intdiv, X_is_LHS)
}

multiply_coo_by_dense_ignore_NAs_logical <- function(ii, jj, xx, dvec, nrows, ncols) {
    .Call(`_MatrixExtra_multiply_coo_by_dense_ignore_NAs_logical`, ii, jj, xx, dvec, nrows, ncols)
}

multiply_csr_by_svec_no_NAs <- function(indptr, indices, values, ii_base1, xx, length) {
    .Call(`_MatrixExtra_multiply_csr_by_svec_no_NAs`, indptr, indices, values, ii_base1, xx, length)
}

multiply_csr_by_svec_keep_NAs <- function(indptr, indices, values, ii_base1, xx, ncols, length) {
    .Call(`_MatrixExtra_multiply_csr_by_svec_keep_NAs`, indptr, indices, values, ii_base1, xx, ncols, length)
}

multiply_elemwise_dense_by_svec_numeric <- function(X_, ii, xx, length, keep_NAs) {
    .Call(`_MatrixExtra_multiply_elemwise_dense_by_svec_numeric`, X_, ii, xx, length, keep_NAs)
}

multiply_elemwise_dense_by_svec_integer <- function(X_, ii, xx, length, keep_NAs) {
    .Call(`_MatrixExtra_multiply_elemwise_dense_by_svec_integer`, X_, ii, xx, length, keep_NAs)
}

multiply_elemwise_dense_by_svec_logical <- function(X_, ii, xx, length, keep_NAs) {
    .Call(`_MatrixExtra_multiply_elemwise_dense_by_svec_logical`, X_, ii, xx, length, keep_NAs)
}

multiply_elemwise_dense_by_svec_float32 <- function(X_, ii, xx, length, keep_NAs) {
    .Call(`_MatrixExtra_multiply_elemwise_dense_by_svec_float32`, X_, ii, xx, length, keep_NAs)
}

concat_indptr2 <- function(ptr1, ptr2) {
    .Call(`_MatrixExtra_concat_indptr2`, ptr1, ptr2)
}

concat_csr_batch <- function(objects, out) {
    .Call(`_MatrixExtra_concat_csr_batch`, objects, out)
}

check_is_seq <- function(indices) {
    .Call(`_MatrixExtra_check_is_seq`, indices)
}

check_is_rev_seq <- function(indices) {
    .Call(`_MatrixExtra_check_is_rev_seq`, indices)
}

reverse_rows_numeric <- function(indptr, indices, values) {
    .Call(`_MatrixExtra_reverse_rows_numeric`, indptr, indices, values)
}

reverse_rows_logical <- function(indptr, indices, values) {
    .Call(`_MatrixExtra_reverse_rows_logical`, indptr, indices, values)
}

reverse_rows_binary <- function(indptr, indices) {
    .Call(`_MatrixExtra_reverse_rows_binary`, indptr, indices)
}

reverse_columns_inplace_numeric <- function(indptr, indices_, values_, ncol) {
    invisible(.Call(`_MatrixExtra_reverse_columns_inplace_numeric`, indptr, indices_, values_, ncol))
}

reverse_columns_inplace_logical <- function(indptr, indices_, values_, ncol) {
    invisible(.Call(`_MatrixExtra_reverse_columns_inplace_logical`, indptr, indices_, values_, ncol))
}

reverse_columns_inplace_binary <- function(indptr, indices_, values_, ncol) {
    invisible(.Call(`_MatrixExtra_reverse_columns_inplace_binary`, indptr, indices_, values_, ncol))
}

copy_csr_rows_numeric <- function(indptr, indices, values, rows_take) {
    .Call(`_MatrixExtra_copy_csr_rows_numeric`, indptr, indices, values, rows_take)
}

copy_csr_rows_logical <- function(indptr, indices, values, rows_take) {
    .Call(`_MatrixExtra_copy_csr_rows_logical`, indptr, indices, values, rows_take)
}

copy_csr_rows_binary <- function(indptr, indices, rows_take) {
    .Call(`_MatrixExtra_copy_csr_rows_binary`, indptr, indices, rows_take)
}

copy_csr_rows_col_seq_numeric <- function(indptr, indices, values, rows_take, cols_take, index1) {
    .Call(`_MatrixExtra_copy_csr_rows_col_seq_numeric`, indptr, indices, values, rows_take, cols_take, index1)
}

copy_csr_rows_col_seq_logical <- function(indptr, indices, values, rows_take, cols_take, index1) {
    .Call(`_MatrixExtra_copy_csr_rows_col_seq_logical`, indptr, indices, values, rows_take, cols_take, index1)
}

copy_csr_rows_col_seq_binary <- function(indptr, indices, rows_take, cols_take, index1) {
    .Call(`_MatrixExtra_copy_csr_rows_col_seq_binary`, indptr, indices, rows_take, cols_take, index1)
}

copy_csr_arbitrary_numeric <- function(indptr, indices, values, rows_take, cols_take) {
    .Call(`_MatrixExtra_copy_csr_arbitrary_numeric`, indptr, indices, values, rows_take, cols_take)
}

copy_csr_arbitrary_logical <- function(indptr, indices, values, rows_take, cols_take) {
    .Call(`_MatrixExtra_copy_csr_arbitrary_logical`, indptr, indices, values, rows_take, cols_take)
}

copy_csr_arbitrary_binary <- function(indptr, indices, rows_take, cols_take) {
    .Call(`_MatrixExtra_copy_csr_arbitrary_binary`, indptr, indices, rows_take, cols_take)
}

repeat_indices_n_times <- function(indices, remainder, ix_length, desired_length) {
    .Call(`_MatrixExtra_repeat_indices_n_times`, indices, remainder, ix_length, desired_length)
}

extract_single_val_csr_numeric <- function(indptr, indices, values, row, col) {
    .Call(`_MatrixExtra_extract_single_val_csr_numeric`, indptr, indices, values, row, col)
}

extract_single_val_csr_logical <- function(indptr, indices, values, row, col) {
    .Call(`_MatrixExtra_extract_single_val_csr_logical`, indptr, indices, values, row, col)
}

extract_single_val_csr_binary <- function(indptr, indices, row, col) {
    .Call(`_MatrixExtra_extract_single_val_csr_binary`, indptr, indices, row, col)
}

slice_coo_single_numeric <- function(ii, jj, xx, i, j) {
    .Call(`_MatrixExtra_slice_coo_single_numeric`, ii, jj, xx, i, j)
}

slice_coo_single_logical <- function(ii, jj, xx, i, j) {
    .Call(`_MatrixExtra_slice_coo_single_logical`, ii, jj, xx, i, j)
}

slice_coo_single_binary <- function(ii, jj, i, j) {
    .Call(`_MatrixExtra_slice_coo_single_binary`, ii, jj, i, j)
}

slice_coo_arbitrary_numeric <- function(ii, jj, xx, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols) {
    .Call(`_MatrixExtra_slice_coo_arbitrary_numeric`, ii, jj, xx, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols)
}

slice_coo_arbitrary_logical <- function(ii, jj, xx, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols) {
    .Call(`_MatrixExtra_slice_coo_arbitrary_logical`, ii, jj, xx, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols)
}

slice_coo_arbitrary_binary <- function(ii, jj, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols) {
    .Call(`_MatrixExtra_slice_coo_arbitrary_binary`, ii, jj, rows_take_base1, cols_take_base1, all_i, all_j, i_is_seq, j_is_seq, i_is_rev_seq, j_is_rev_seq, nrows, ncols)
}

